# Generated by Django 6.0 on 2026-01-05 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='uploads/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_frames', models.IntegerField(default=0)),
                ('accident_frames', models.IntegerField(default=0)),
                ('detection_rate', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('smoothing_frames', models.IntegerField(default=15)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
